### ISSUE TITLE
Selection network events

### ISSUE THREAD

**Issue by annemiekvberkel** [alemoro/Calcium_networkAnalysis#2]
Hi Ale,

I am playing around with the analysis. Loading, detecting and quantifying spikes works very good. However, I am now struggling with the detection of synchronous/network events. Synchronous events are not picked up (see ppt for example), most probably because the events vary a tiny bit in time. 

How many frames are allowed to deviate between cells to still belong to same synchronous event? Can we adjust this?
[210429_question Ale.pptx](https://github.com/alemoro/Calcium_networkAnalysis/files/6397478/210429_question.Ale.pptx)

**Comment by alemoro** [comment]
I see. For now the definition of "synchronous event" is pretty strict to two frames around one spike.
I can make a quick fix that allows selecting the number of frames to consider for synchronicity, perhaps by Wednesday next week. There are then two options that I can imagine. One is to see what EvA is doing and use the same way to define synchronicity. The other is to use the Sun/Sudhof method which calculates synchronicity from the averaged trace. The downside of that method is that we will potentially lose the information of the number of neurons participating. For both these fixes, I might need another couple of weeks.

**Comment by annemiekvberkel** [comment]
Hi Ale, thanks a lot for your quick reply! Yes it would be great if we can expand the number of frames to be considered, and see how that works out. e.g. in EvA, they mention that the binarized traces were convolved with a Gaussian kernel of five frames width around the start point of each event.

Then we can see if we need other fixes. 

Thanks!!!

**Comment by alemoro** [comment]
Hi Annemiek.

I implemented the detection of synchronous events like it is in EvA. Could you give it a try and let me know how this implementation is? I still use a hard-coded threshold and Gaussian window, but they will be easy to add as options when I know it's working as expected.

**Comment by annemiekvberkel** [comment]
Hi Ale,

Thanks a lot!! This works very well and as expected. Conceptual question: EvA uses EventStartIdx to detect network activity, i think you use PeakIdx? I think there's something to say for both, but 'rise time' might be affected in my experimental condition I would say that maybe EventStartIdx is better? Although it should be equal among neurons in one FOV, so it probably won't change much.

Thanks again!
