### ISSUE TITLE
Error Index in position 2 is invalid. Array indices must be positive integers or logical values.

### ISSUE THREAD

**Issue by annemiekvberkel** [alemoro/Calcium_networkAnalysis#3]
Hi Ale,

for one of my files I get the following error:

Index in position 2 exceeds array bounds (must not exceed 512).

Error in networkActivityApp/getIntensityvalues (line 333)
                    roiIntensities(roi,:) =
                    mean(mean(imgData(tempMask{roi,1}(1):tempMask{roi,1}(2),
                    tempMask{roi,2}(1):tempMask{roi,2}(3), :))); % 5 is the radius, needs to
                    be set as option

Error in networkActivityApp/DicMenuPlaceRoiSelected (line 943)
            getIntensityvalues(app)
 
Error while evaluating Menu Callback.

I cannot seem to continue (only when closing the App). Could you help me with this error? 

Thanks a lot,

Annemiek

**Comment by alemoro** [comment]
This error occurred when the ROI was selected too close to the edge of the image. It is not fixed in the latest version.
